### ISSUE TITLE
better docs or readme

### ISSUE THREAD

**Issue by philippfrenzel** [e-frank/yii2-knockout#2]
Hi, can you pls. enhance the docs, as I would love to use knockout and it seems like you understand the libs pretty good... maybe you can link breeze.js too, so "offline" sites will be supported too?

Thanks phil

**Comment by e-frank** [comment]
@philippfrenzel I am just rewriting a lot of code, docs will follow.
I haven't used breeze yet, but it looks interesting.
could you describe your use cases in some detail?

**Comment by philippfrenzel** [comment]
I have the problem of "sales" people running the app on a tablet without the security of having internet connection. So the data collection should be available on or offline - breeze syncs data with localStorage or if online with the server;) And Knockout.js will handle the client side onepage data collector... angular is to much in my eyes...:)

Thanks Phil

**Comment by e-frank** [comment]
You are right. angular, ember, & co are way too much - that's why i picked knockout.

_breeze_:
i think breeze doesn't do anything automatically - you will have to code online/offline logic yourself. moreover it is coupled to entity framework. in addition to creating knockout viewmodels, you would also have to create/generate breeze metadata + validators ... again.
if you have got that far, you have to take care of update/delete operations - just think of server side business logic (changing values).
if you don't need any of these, frameworkless localstorage will work fine.
i don't know how to write a meaningful and reusable extension for breeze - that's why i would not go this way. 

alternative: check out meteor and firebase

**Comment by philippfrenzel** [comment]
Hi,

thanks for the answer… So I thought breeze does the sync job:( With the entity manager… but localStorage is ok for me;) Looking forward to your docs and thanks for the links!

Cheers Philipp=

**Comment by e-frank** [comment]
if you can provide me with some **working** breeze html & js source code, i can try to generate the metadata from yii models. but i don't think it's worth it.

**Comment by philippfrenzel** [comment]
i totally agree… I’m more interested in your knockout libs for yii2 - hope you publish some simple docs soon;)
